<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Http;
use Inertia\Inertia;
use Illuminate\Http\Request;
use App\Models\SheetOrder;
use App\Support\CountryAccess;

class AiController extends Controller
{
    private string $ollamaUrl;
    private string $model;
    private string $systemPrompt;

    public function __construct()
    {
        $this->ollamaUrl = env('AI_OLLAMA_URL', 'http://127.0.0.1:11434/api/generate');
        $this->model     = env('AI_OLLAMA_MODEL', 'qwen3.5:2b');

        $this->systemPrompt = <<<PROMPT
You are an AI assistant for RealDeal Courier, a logistics and courier management platform operating in Kenya, Tanzania, Uganda, and Zambia.

Your primary role is to help office staff with tasks such as:
- Creating and managing courier orders
- Looking up order status
- Summarizing delivery information
- Answering questions about shipments

When the user asks to create an order, extract the following fields and return them in JSON format:
{
  "order_date": "",
  "amount": null,
  "client_name": "",
  "address": "",
  "phone": "",
  "alt_no": "",
  "country": "",
  "city": "",
  "product_name": "",
  "quantity": null,
  "merchant": "",
  "status": "Scheduled"
}

CRITICAL RULES:
- The "merchant" is the SHOP or STORE NAME that is selling the product (e.g. "RealDeal Shop", "Jane's Store"). It is NEVER the client/customer name.
- The "client_name" is the CUSTOMER receiving the order.
- If the user has NOT explicitly provided a merchant/shop/store name, you MUST ask: "Which merchant/shop is this order for?" before returning JSON. Do NOT guess, infer, or copy the client name into the merchant field.
- The "status" field defaults to "Scheduled" if not specified.
- The "order_no" will be auto-generated by the system, do not include it.
- "amount" should be the total order amount (e.g. 2800).
- "quantity" should be a number (e.g. 1).
- If any other field is missing, set it to null and ask the user for it.
Always respond in clear, professional English.
Keep responses concise and actionable.
PROMPT;
    }

    /**
     * Render the AI chat page.
     */
    public function index()
    {
        return Inertia::render('ai/index');
    }

    /**
     * Handle a chat message from the user.
     */
    public function ask(Request $request)
    {
        $request->validate([
            'message' => 'required|string|max:2000',
        ]);

        $message = trim($request->input('message'));

        // Build the full prompt with system context
        $fullPrompt = $this->systemPrompt . "\n\nUser: " . $message . "\n\nAssistant:";

        try {
            Log::info('AI ASK: User message', ['message' => $message]);

            $response = Http::timeout(120)->post($this->ollamaUrl, [
                'model'  => $this->model,
                'prompt' => $fullPrompt,
                'stream' => false,
                'options' => [
                    'num_predict' => 1000,   // Enough for full JSON order + explanation
                    'temperature' => 0.3,    // Low = deterministic, great for structured data
                    'top_p'       => 0.9,
                    'stop'        => ['User:', '\nUser:'], // Prevent hallucinated multi-turn
                ],
            ]);

            if (!$response->successful()) {
                Log::error('AI ASK: Ollama API error', [
                    'status' => $response->status(),
                    'body'   => $response->body(),
                ]);
                return response()->json([
                    'success' => false,
                    'reply'   => 'AI service error. Please try again.',
                ], 500);
            }

            $reply = trim($response->json('response') ?? '');

            if (empty($reply)) {
                return response()->json([
                    'success' => false,
                    'reply'   => 'No response from AI. Please try again.',
                ], 500);
            }

            // Strip DeepSeek-R1 <think>...</think> reasoning blocks (not for users)
            $reply = preg_replace('/<think>.*?<\/think>/s', '', $reply);
            $reply = trim($reply);

            // Detect if response contains a JSON order object
            $orderData = $this->extractOrderJson($reply);

            Log::info('AI ASK: Response received', [
                'reply'      => $reply,
                'has_order'  => !is_null($orderData),
            ]);

            return response()->json([
                'success'    => true,
                'reply'      => $reply,
                'order_data' => $orderData, // null if no order detected
            ]);

        } catch (\Illuminate\Http\Client\ConnectionException $e) {
            Log::error('AI ASK: Ollama connection failed', ['error' => $e->getMessage()]);
            return response()->json([
                'success' => false,
                'reply'   => 'Could not connect to AI service. Please ensure Ollama is running.',
            ], 503);

        } catch (\Exception $e) {
            Log::error('AI ASK: Fatal error', ['error' => $e->getMessage()]);
            return response()->json([
                'success' => false,
                'reply'   => 'Service temporarily unavailable. Please try again.',
            ], 500);
        }
    }

    /**
     * Check Ollama service health.
     */
    public function health()
    {
        try {
            $baseUrl = str_replace('/api/generate', '', $this->ollamaUrl);
            $response = Http::timeout(5)->get($baseUrl);

            return response()->json([
                'status'  => 'online',
                'model'   => $this->model,
                'message' => 'Ollama is running.',
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'status'  => 'offline',
                'model'   => $this->model,
                'message' => 'Ollama is not reachable.',
            ], 503);
        }
    }

    /**
     * List all locally available Ollama models.
     */
    public function models()
    {
        try {
            $baseUrl  = str_replace('/api/generate', '', $this->ollamaUrl);
            $response = Http::timeout(10)->get($baseUrl . '/api/tags');

            if (!$response->successful()) {
                return response()->json(['models' => []]);
            }

            $models = collect($response->json('models') ?? [])
                ->map(fn($m) => [
                    'name' => $m['name'],
                    'size' => $this->formatBytes($m['size'] ?? 0),
                ])
                ->values();

            return response()->json(['models' => $models]);

        } catch (\Exception $e) {
            Log::error('AI MODELS: Failed to fetch models', ['error' => $e->getMessage()]);
            return response()->json(['models' => []]);
        }
    }

    /**
     * Extract JSON order data from AI response if present.
     */
    private function extractOrderJson(string $reply): ?array
    {
        if (preg_match('/\{[\s\S]*"client_name"[\s\S]*\}/m', $reply, $matches)) {
            $decoded = json_decode($matches[0], true);
            if (json_last_error() === JSON_ERROR_NONE) {
                return $decoded;
            }
        }
        return null;
    }

    /**
     * Format bytes to human-readable size.
     */
    private function formatBytes(int $bytes): string
    {
        if ($bytes >= 1073741824) return round($bytes / 1073741824, 1) . ' GB';
        if ($bytes >= 1048576)    return round($bytes / 1048576, 1) . ' MB';
        return $bytes . ' B';
    }

    /**
     * Create an order from AI-extracted data.
     */
    public function createOrder(Request $request)
    {
        $user = $request->user();

        if (!$user) {
            return response()->json(['success' => false, 'message' => 'Unauthenticated.'], 401);
        }

        $validated = $request->validate([
            'order_date'    => 'required|date',
            'amount'        => 'required|numeric',
            'quantity'      => 'required|integer',
            'client_name'   => 'required|string|max:255',
            'address'       => 'nullable|string|max:255',
            'phone'         => 'nullable|string|max:50',
            'alt_no'        => 'nullable|string|max:255',
            'country'       => 'nullable|string|max:255',
            'city'          => 'nullable|string|max:255',
            'product_name'  => 'nullable|string|max:255',
            'merchant'      => 'nullable|string|max:255',
            'status'        => 'required|string|max:50',
            'instructions'  => 'nullable|string',
        ]);

        $validated['country'] = CountryAccess::resolveCountryNameForWrite($user, $validated['country'] ?? null);

        $validated['order_no'] = $this->getNextOrderNumber($validated['merchant'] ?? 'DefaultMerchant');
        $validated['order_type'] = 'ai-created';
        $validated['updated_at'] = now();

        $order = SheetOrder::create($validated);

        Log::info('AI ORDER: Created', ['order_no' => $order->order_no, 'user' => $user->name]);

        return response()->json([
            'success' => true,
            'message' => "Order {$order->order_no} created successfully.",
            'order' => $order,
        ]);
    }

    /**
     * Generate next order number for a given merchant.
     */
    private function getNextOrderNumber(string $sheetName): string
    {
        $lastNumber = SheetOrder::where('sheet_name', $sheetName)
            ->whereRaw('order_no REGEXP "^[A-Z]+[0-9]+$"')
            ->selectRaw('MAX(CAST(SUBSTRING(order_no, LENGTH(REGEXP_SUBSTR(order_no, "^[A-Z]+")) + 1) AS UNSIGNED)) as max_number,
                         REGEXP_SUBSTR(order_no, "^[A-Z]+") as prefix')
            ->groupBy('prefix')
            ->orderByDesc('max_number')
            ->first();

        $nextNumber = 1;
        $prefix = 'ORD';

        if ($lastNumber) {
            $prefix = $lastNumber->prefix;
            $nextNumber = $lastNumber->max_number + 1;
        }

        return $prefix . $nextNumber;
    }
}
